### ISSUE TITLE
Add container barcode and GUIDS to NPS spreadsheet

### ISSUE THREAD

**Issue by StefanieBond** [camwebb/ALA-informatics#13]
#13 Adding the container barcode and GUIDS to the NPS spreadsheet for the annual report for the herbarium. The spreadsheet is also in the Google drive folder. Thanks!
[2022_UAMN_NPSConsolidatedInventory.xls](https://github.com/camwebb/ALA-informatics/files/8978691/2022_UAMN_NPSConsolidatedInventory.xls)

**Comment by camwebb** [comment]
Done. I searched on ALAAC if it had one, then the NPS specimen code. About 2/3 of the specimens now have GUIDs and barcode. There were a few GUIDs that had no barcodes. Please see spreadsheet on google drive.
