### ISSUE TITLE
Understand the new locality system in Arctos

### ISSUE THREAD

**Issue by camwebb** [camwebb/ALA-informatics#38]
Just discovered from @mabreslin (thanks!) that just last week [major changes](https://github.com/ArctosDB/arctos/issues/5138) were made to the Higher Geography model. We all need to understand this better. Please don't make new bulk uploads (or even one-by-one locality edits) until we all understand this better. We can use this Issue thread to keep track of what we find out. Thanks.

**Comment by camwebb** [comment]
Ok, so as far as I understand, nothing has changed in the data structure, nor in the bulkloader(s) (tested and working). But the options for Higher Geography are far fewer - basically just country and county (following [GADM](https://gadm.org/maps.html)). Everything else should be in the specific locality (remember, written from specific/fine scale to larger). There is the option to set locality attribute `feature` to a Park's name (if it's in the [code table](https://arctos.database.museum/info/ctDocumentation.cfm?table=ctfeature)), and I'm [waiting](https://github.com/ArctosDB/arctos/issues/5207) to see if that is recommended or not.

Anyone else discover anything?

**Comment by szaborac** [comment]
I've found that automatic georeferencing cannot be relied upon, though it
IS a little closer than it was a couple of weeks ago (when it automatically
georeferenced a Yukon Territory sample in Ontario).

In Alaska, using Quads makes sense. We don't have counties. Why the change?

**Comment by mabreslin** [comment]
Hi,
All of the specimens that got changed moved the park name over to be a
feature, so it seems like a safe choice. Quads can also be listed as a
feature, though I'm sure including them in the specific locality would also
be fine.

**Comment by camwebb** [comment]
I guess the existing Higher Geography system was getting unwieldy and reconciling to GADM made the best sense. The geographic elements smaller than county can be stored elsewhere. In Alaska county more or less = Borough. Search for Alaska in <https://arctos.database.museum/place.cfm?sch=geog>. The Boroughs are all "assertable" i.e., can be used in the higher geog field.

Please read the [new documentation](https://handbook.arctosdb.org/how_to/How-to-understand-the-Arctos-Locality-Model.html). And [here](https://handbook.arctosdb.org/documentation/higher-geography.html).

[According to](https://github.com/ArctosDB/arctos/issues/5207#issuecomment-1309485183) Dusty, using the locality attribute `feature=ParkName` is the most formal way to specify a park if you needed to, but just putting the park name in the specific locality should be sufficient.  

I think we're good to go ahead. Closing...
